[package]
name = "circuit_macro"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
